#!/usr/bin/env bash
#This script Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
term_handler() {
  echo "I hate the kill command"
  delete_pid_file
  exit 0
}
int_handler() {
  echo "Y U no love me?!"
}
delete_pid_file() {
  if [ -f "/var/run/myscript.pid" ]; then
    rm "/var/run/myscript.pid"
  fi
}
trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT
pid=$
echo $pid > /var/run/myscript.pid
while true; do
  echo "To infinity and beyond"
  sleep 1
done
