#!/usr/bin/env bash
#This script manages manage_my_process
start() {
  ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"
}
stop() {
  sudo kill $(cat /var/run/my_process.pid)
  && rm -rf /var/run/my_process.pid
  echo "manage_my_process stopped"
}
restart() {
  ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  sudo kill $(cat /var/run/my_process.pid)
  && rm -rf /var/run/my_process.pid
  echo "manage_my_process restarted"
}
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac
