#!/usr/bin/env bash
#This script displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process
# shellcheck disable=SC2009
ps_output=$(ps auxf | grep bash)
echo "$ps_output" | grep bash
