#!/usr/bin/env bash
#This script displays lthe PID, along with the process name, of processes whose name contain the word bash
# shellcheck disable=SC2009
ps_output=$(pgrep -l bash)
echo "$ps_output"
