#!/usr/bin/env bash
#This script displays To infinity and beyond indefinitely With a sleep 2 in between each iteration I am invincible!!! when receiving a SIGTERM signal
term_handler() {
  echo "I am invincible!!!"
  exit 0
}
trap term_handler SIGTERM
while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
